server.servlet.context-path = /32b4dc6e4ce74714b7823c8ec64ea9f3
spring.profiles.active=db,core,wx,server
spring.messages.encoding=UTF-8
server.port=9811
server.session.timeout=18000
#\u6a21\u677f\u5f15\u64ce\u914d\u7f6e
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.servlet.content-type=text/html
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
logging.config=classpath:log_config/logback-spring.xml
#\u5f00\u542fMyBatis\u7684\u4e8c\u7ea7\u7f13\u5b58
mybatis.configuration.cache-enabled=true
#\u8bbe\u7f6e\u5206\u9875
pagehelper.helperDialect=mysql
pagehelper.params=count=countSql
pagehelper.reasonable=true
pagehelper.supportMethodsArguments=true
netty.port=14721
netty.ip=103.45.156.174
lineName=\u7693\u6708\u5f53\u7a7a
lineNum=1
jifenhuishou = 10
tongtiantaTao = 374000
wendaoxiaozi = E:/\u95ee\u9053\u624b\u6e38/wendaoxiaozi/wendaoxiaozi.bat
menu_auths = hyjj,autoTalk