package com.fengshen.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.fengshen.db.domain.Chara_Statue;
import com.fengshen.db.domain.Chara_StatueExample;

public interface Chara_StatueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chara_statue
     *
     * @mbg.generated Tue Feb 11 00:01:53 CST 2020
     */
    long countByExample(Chara_StatueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chara_statue
     *
     * @mbg.generated Tue Feb 11 00:01:53 CST 2020
     */
    int deleteByExample(Chara_StatueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chara_statue
     *
     * @mbg.generated Tue Feb 11 00:01:53 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chara_statue
     *
     * @mbg.generated Tue Feb 11 00:01:53 CST 2020
     */
    int insert(Chara_Statue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chara_statue
     *
     * @mbg.generated Tue Feb 11 00:01:53 CST 2020
     */
    int insertSelective(Chara_Statue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chara_statue
     *
     * @mbg.generated Tue Feb 11 00:01:53 CST 2020
     */
    List<Chara_Statue> selectByExampleWithBLOBs(Chara_StatueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chara_statue
     *
     * @mbg.generated Tue Feb 11 00:01:53 CST 2020
     */
    List<Chara_Statue> selectByExample(Chara_StatueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chara_statue
     *
     * @mbg.generated Tue Feb 11 00:01:53 CST 2020
     */
    Chara_Statue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chara_statue
     *
<<<<<<< HEAD
     * @mbg.generated Mon Feb 10 16:21:30 CST 2020
=======
     * @mbg.generated Tue Feb 11 00:01:53 CST 2020
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chara_statue
     *
<<<<<<< HEAD
     * @mbg.generated Mon Feb 10 16:21:30 CST 2020
=======
     * @mbg.generated Tue Feb 11 00:01:53 CST 2020
>>>>>>> 0fd853b00d744a9a2f2f6e388d0d1a0d6a39dc35
     */
    int updateByExampleWithBLOBs(@Param("record") Chara_Statue record, @Param("example") Chara_StatueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chara_statue
     *
<<<<<<< HEAD
     * @mbg.generated Mon Feb 10 16:21:30 CST 2020
=======
     * @mbg.generated Tue Feb 11 00:01:53 CST 2020
>>>>>>> 0fd853b00d744a9a2f2f6e388d0d1a0d6a39dc35
     */
    int updateByExample(@Param("record") Chara_Statue record, @Param("example") Chara_StatueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chara_statue
     *
<<<<<<< HEAD
     * @mbg.generated Mon Feb 10 16:21:30 CST 2020
=======
     * @mbg.generated Tue Feb 11 00:01:53 CST 2020
>>>>>>> 0fd853b00d744a9a2f2f6e388d0d1a0d6a39dc35
     */
    int updateByPrimaryKeySelective(Chara_Statue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chara_statue
     *
<<<<<<< HEAD
     * @mbg.generated Mon Feb 10 16:21:30 CST 2020
=======
     * @mbg.generated Tue Feb 11 00:01:53 CST 2020
>>>>>>> 0fd853b00d744a9a2f2f6e388d0d1a0d6a39dc35
     */
    int updateByPrimaryKeyWithBLOBs(Chara_Statue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chara_statue
     *
<<<<<<< HEAD
     * @mbg.generated Mon Feb 10 16:21:30 CST 2020
=======
     * @mbg.generated Tue Feb 11 00:01:53 CST 2020
>>>>>>> 0fd853b00d744a9a2f2f6e388d0d1a0d6a39dc35
     */
    int updateByPrimaryKey(Chara_Statue record);
}