package com.fengshen.db.dao;

import org.apache.ibatis.annotations.Param;

import com.fengshen.db.domain.ChargePoint;
import com.fengshen.db.domain.ChargePointExample;

import java.util.List;

public interface ChargePointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_point
     *
     * @mbg.generated Fri Feb 14 18:41:38 CST 2020
     */
    long countByExample(ChargePointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_point
     *
     * @mbg.generated Fri Feb 14 18:41:38 CST 2020
     */
    int deleteByExample(ChargePointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_point
     *
     * @mbg.generated Fri Feb 14 18:41:38 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_point
     *
     * @mbg.generated Fri Feb 14 18:41:38 CST 2020
     */
    int insert(ChargePoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_point
     *
     * @mbg.generated Fri Feb 14 18:41:38 CST 2020
     */
    int insertSelective(ChargePoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_point
     *
     * @mbg.generated Fri Feb 14 18:41:38 CST 2020
     */
    List<ChargePoint> selectByExample(ChargePointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_point
     *
     * @mbg.generated Fri Feb 14 18:41:38 CST 2020
     */
    ChargePoint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_point
     *
     * @mbg.generated Fri Feb 14 18:41:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") ChargePoint record, @Param("example") ChargePointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_point
     *
     * @mbg.generated Fri Feb 14 18:41:38 CST 2020
     */
    int updateByExample(@Param("record") ChargePoint record, @Param("example") ChargePointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_point
     *
     * @mbg.generated Fri Feb 14 18:41:38 CST 2020
     */
    int updateByPrimaryKeySelective(ChargePoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_point
     *
     * @mbg.generated Fri Feb 14 18:41:38 CST 2020
     */
    int updateByPrimaryKey(ChargePoint record);
}