package com.fengshen.db.domain;

public class ChargePoint {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge_point.id
     *
     * @mbg.generated Fri Feb 14 18:41:38 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge_point.no
     *
     * @mbg.generated Fri Feb 14 18:41:38 CST 2020
     */
    private Integer no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge_point.awardStr
     *
     * @mbg.generated Fri Feb 14 18:41:38 CST 2020
     */
    private String awardstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge_point.point
     *
     * @mbg.generated Fri Feb 14 18:41:38 CST 2020
     */
    private Integer point;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charge_point.left_num
     *
     * @mbg.generated Fri Feb 14 18:41:38 CST 2020
     */
    private Integer leftNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_point
     *
     * @mbg.generated Fri Feb 14 18:41:38 CST 2020
     */
    public ChargePoint(Integer id, Integer no, String awardstr, Integer point, Integer leftNum) {
        this.id = id;
        this.no = no;
        this.awardstr = awardstr;
        this.point = point;
        this.leftNum = leftNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_point
     *
     * @mbg.generated Fri Feb 14 18:41:38 CST 2020
     */
    public ChargePoint() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge_point.id
     *
     * @return the value of charge_point.id
     *
     * @mbg.generated Fri Feb 14 18:41:38 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge_point.id
     *
     * @param id the value for charge_point.id
     *
     * @mbg.generated Fri Feb 14 18:41:38 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge_point.no
     *
     * @return the value of charge_point.no
     *
     * @mbg.generated Fri Feb 14 18:41:38 CST 2020
     */
    public Integer getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge_point.no
     *
     * @param no the value for charge_point.no
     *
     * @mbg.generated Fri Feb 14 18:41:38 CST 2020
     */
    public void setNo(Integer no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge_point.awardStr
     *
     * @return the value of charge_point.awardStr
     *
     * @mbg.generated Fri Feb 14 18:41:38 CST 2020
     */
    public String getAwardstr() {
        return awardstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge_point.awardStr
     *
     * @param awardstr the value for charge_point.awardStr
     *
     * @mbg.generated Fri Feb 14 18:41:38 CST 2020
     */
    public void setAwardstr(String awardstr) {
        this.awardstr = awardstr == null ? null : awardstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge_point.point
     *
     * @return the value of charge_point.point
     *
     * @mbg.generated Fri Feb 14 18:41:38 CST 2020
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge_point.point
     *
     * @param point the value for charge_point.point
     *
     * @mbg.generated Fri Feb 14 18:41:38 CST 2020
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charge_point.left_num
     *
     * @return the value of charge_point.left_num
     *
     * @mbg.generated Fri Feb 14 18:41:38 CST 2020
     */
    public Integer getLeftNum() {
        return leftNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charge_point.left_num
     *
     * @param leftNum the value for charge_point.left_num
     *
     * @mbg.generated Fri Feb 14 18:41:38 CST 2020
     */
    public void setLeftNum(Integer leftNum) {
        this.leftNum = leftNum;
    }
}